version: '3.8'
services:
  golang_app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - golang_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
